Make BeBuilder work on x86-gcc2
HaikuArchives/BeBuilder pull request #1
Opened 2016-12-12 21:03 UTC by ohnx

Untested for gcc5.

2016-12-13 20:59 UTC, waddlesplash requested changes

2016-12-13 20:59 UTC, waddlesplash commented on .gitignore
> +objects.x86-gcc2-release/
Make this just `objects*/`.

2016-12-17 00:59 UTC, waddlesplash approved these changes

2016-12-17 00:59 UTC, merged

2016-12-17 00:59 UTC, waddlesplash commented
GCI task link? (or was it already approved)

2016-12-17 02:45 UTC, ohnx commented
Was already approved; thanks :)