Get BeBuilder to compile on Haiku
HaikuArchives/BeBuilder pull request #7
Opened 2018-11-14 03:56 UTC by bach5000

This PR comes with a Haiku makefile and a modified README.
Has been tested on x86_64.

2018-11-14 04:03 UTC, scottmc commented
Does this pull request make the other open pull request obsolete?

2018-11-14 06:07 UTC, owenca commented on V0.5.2BeBuilder/Makefile
> +		./CodeGenerator/SliderCodeGenerator.cpp
All the `./` prefixes are redundant.

2018-11-14 06:09 UTC, owenca requested changes

2018-11-14 06:09 UTC, owenca commented on V0.5.2BeBuilder/Makefile
> +		./Resources/WindowResource.rdef
Same here. And they can fit in one line, right?

2018-11-14 06:09 UTC, owenca commented on V0.5.2BeBuilder/Makefile
> +		root
I would put all the libraries on the same line, and you don't need `root`.

2018-11-14 12:53 UTC, bach5000 commented
@scottmc I believe it does make the other one obsolete: the other PR still has a BeOS Makefile.
@owenca Thanks for reviewing! Will get those fixes committed in a moment.

2018-11-14 15:40 UTC, bach5000 commented
@owenca Applied the changes :)

2018-11-19 17:09 UTC, scottmc commented
This working now?  How about a refresh of the readme with a screenshot?

2018-11-20 01:02 UTC, bach5000 commented
@scottmc: The changes were only cosmetic changes, so I don't think a new screenshot would be necessary :)

2019-12-08 12:41 UTC, merged